import { StyleSheet } from "react-native";
import { colors, layout } from "./theme";

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    width: "100%",
    maxWidth: layout.pageMaxWidth,
    alignSelf: "center",
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    backgroundColor: colors.card,
    borderRadius: layout.radiusLarge,
    paddingVertical: 22,
    paddingHorizontal: 28,
    marginBottom: 44,
    gap: 12,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  logo: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: 0,
  },
  hero: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: 20,
    marginBottom: 30,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 6,
    textTransform: "uppercase",
  },
  logoutButton: {
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  profilePageActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
    marginTop: 2,
  },
  profileLogoutButton: {
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 28,
    alignItems: "center",
    minWidth: 220,
  },
  profileDeleteButton: {
    borderColor: colors.danger,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 28,
    alignItems: "center",
    minWidth: 220,
  },
  profileDeleteButtonText: {
    color: colors.danger,
    fontWeight: "700",
  },
  logoutText: {
    color: colors.primary,
    fontWeight: "600",
  },
  secondaryButton: {
    backgroundColor: colors.input,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  secondaryButtonText: {
    color: colors.text,
    fontWeight: "700",
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 22,
    alignItems: "center",
  },
  primaryButtonText: {
    color: colors.textDark,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: layout.radiusLarge,
    padding: 22,
    marginBottom: 18,
  },
  title: {
    color: colors.text,
    fontSize: 36,
    fontWeight: "600",
    marginBottom: 8,
  },
  label: {
    color: colors.muted,
    marginTop: 14,
    marginBottom: 8,
  },
  profileFormActions: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginTop: 24,
    marginBottom: 24,
  },
  profileSaveButton: {
    minWidth: 190,
  },
  profileReadOnlySection: {
    borderTopColor: colors.inputBorder,
    borderTopWidth: 1,
    paddingTop: 20,
  },
  profileDetailGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 14,
  },
  profileDetailItem: {
    flexGrow: 1,
    flexBasis: 260,
    backgroundColor: colors.backgroundDeep,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
  },
  profileDetailLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
    textTransform: "uppercase",
  },
  profileDetailValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
  },
  muted: {
    color: colors.muted,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    gap: 16,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "600",
    marginBottom: 4,
  },
  countBadge: {
    backgroundColor: colors.input,
    color: colors.text,
    borderRadius: 999,
    minWidth: 34,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
    textAlign: "center",
    fontWeight: "700",
  },
  ticketSection: {
    marginBottom: 24,
  },
  ticketCard: {
    backgroundColor: colors.card,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: layout.radiusMedium,
    padding: 18,
    marginBottom: 12,
  },
  ticketCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 12,
  },
  ticketTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "700",
    flex: 1,
  },
  ticketTitleBlock: {
    flex: 1,
  },
  statusPill: {
    backgroundColor: colors.primary,
    color: "#111236",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "700",
  },
  statusPillClosed: {
    backgroundColor: colors.cardSoft,
    color: colors.muted,
  },
  ticketMeta: {
    color: colors.text,
    marginBottom: 6,
  },
  ticketDate: {
    color: colors.muted,
    fontSize: 13,
  },
  messageCard: {
    backgroundColor: colors.card,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: layout.radiusMedium,
    padding: 18,
    marginTop: 10,
  },
  adminMessageCard: {
    borderColor: colors.primary,
    borderWidth: 1,
  },
  messageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  messageSender: {
    color: colors.text,
    fontWeight: "700",
  },
  messageText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
  },
  emptyText: {
    color: colors.muted,
    backgroundColor: colors.card,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: layout.radiusMedium,
    padding: 16,
  },
  loadingState: {
    paddingVertical: 40,
    alignItems: "center",
  },
  input: {
    backgroundColor: colors.input,
    color: colors.text,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
  },
  inputError: {
    borderColor: colors.danger,
    borderWidth: 1,
  },
  textArea: {
    minHeight: 140,
    marginBottom: 16,
  },
  optionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 4,
  },
  optionButton: {
    backgroundColor: colors.input,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  optionButtonSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionButtonText: {
    color: colors.text,
    fontWeight: "700",
  },
  optionButtonTextSelected: {
    color: colors.textDark,
  },
  optionSubtext: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 4,
  },
  optionSubtextSelected: {
    color: colors.textDark,
  },
  errorText: {
    color: colors.danger,
    marginBottom: 12,
    fontWeight: "600",
  },
  fieldErrorText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 6,
    marginBottom: 8,
  },
  attachmentActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 12,
  },
  attachmentList: {
    gap: 6,
    marginTop: 10,
    marginBottom: 12,
  },
  attachmentHelpText: {
    color: colors.muted,
    fontSize: 12,
    marginBottom: 8,
  },
  attachmentErrorText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 8,
  },
  attachmentText: {
    color: colors.text,
    backgroundColor: colors.input,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontSize: 13,
  },
  attachmentDownloadButton: {
    backgroundColor: colors.input,
    borderColor: colors.inputBorder,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  attachmentDownloadText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: "700",
  },
});
